import React from "react";

const Pdata = [
  {
    name: "Men Shirt",
    type: "men",
    discpriton: "New Black Shirt For Men",
    imge: "https://sc04.alicdn.com/kf/Hdae17163cb0a4c1fbb300cc754e19e81l.jpg",
    price: "499",
    categary: "shirt",
  },
  {
    name: "Men Shirt New",
    type: "men",
    discpriton: "New blue Shirt For Men",
    imge: "https://ae01.alicdn.com/kf/HTB1ouCNMVXXXXaOXFXXq6xXFXXXj/New-Autumn-Fashion-Brand-Print-Shirts-Slim-Fit-Shirt-Men-Long-Sleeve-Cotton-Casual-Mens-Shirts.jpg",
    price: "500",
    categary: "shirt",
  },
  {
    name: "Kurta",
    type: "men",
    discpriton: "New Kurta For Men",
    imge: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPttHmqm6luA6CND2BjV7064R1A2o6rJ6rAQ&usqp=CAU",
    price: "2500",
    categary: "kurta",
  },
  {
    name: "Men's Casual Shirt",
    type: "men",
    discpriton: " Shirt Cotton Long Sleeve Button ",
    imge: "https://i.pinimg.com/originals/e4/5a/43/e45a43655c7502a3b053c0261e2d1ec5.jpg",
    price: "699",
    categary: "shirt",
  },
  {
    name: "Men Shirt",
    type: "men",
    discpriton: "Mens Formal Shirts For Men Clothes",
    imge: "https://image.dhgate.com/0x0s/f2-albu-g10-M01-F5-61-rBVaWVyks8SAdU7lAADdjruigfw389.jpg/men-shirt-long-sleeve-mens-shirts-casual.jpg",
    price: "750",
    categary: "kurta",
  },
  {
    name: "WoMen Shirt",
    type: "women",
    discpriton: "Mens Formal Shirts For Men Clothes",
    imge: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl2m3Zx7SRVH_qRUCtW3swDyHHNrOw2royiQ&usqp=CAU",
    price: "750",
    categary: "shirt",
  },
  {
    name: "Girl Shirt",
    type: "men",
    discpriton: "New White Shirt For Girls",
    imge: "https://images-eu.ssl-images-amazon.com/images/I/61gqf3Ufn4L._AC._SR360,460.jpg",
    price: "799",
    categary: "shirt",
  },  {
    name: "Men  Blue Kurta",
    type: "men",
    discpriton: "New Blue kurta For Boys",
    imge: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvVLZdz91nShlXtPequqWbPK0IIVU175SaEg&usqp=CAU",
    price: "7299",
    categary: "shirt",
  },
  {
    name: "Men Shirt",
    type: "men",
    discpriton: "Mens Formal Shirts For Men Clothes",
    imge: "https://image.dhgate.com/0x0s/f2-albu-g10-M01-F5-61-rBVaWVyks8SAdU7lAADdjruigfw389.jpg/men-shirt-long-sleeve-mens-shirts-casual.jpg",
    price: "750",
    categary: "kurta",
  },
  {
    name: "Girl Jeans Shirt",
    type: "men",
    discpriton: "Jeans Shirt High Quality",
    imge: "https://static-01.daraz.pk/p/95fd1da70adfa68fd1c41963e59ce4f9.jpg_340x340q80.jpg_.webp",
    price: "900",
    categary: "shirt",
  },
  {
    name: "woman Casual Shirt",
    type: "men",
    discpriton: " Women Printed Stylish Full Sleeve ",
    imge: "https://looksgud.com/blog/wp-content/uploads/2017/05/sangria-mandarin-collar-full-placket-printed-tunic.jpg",
    price: "999",
    categary: "shirt",
  },
  {
    name: "New Girl Shirt",
    type: "men",
    discpriton: "shirts are designed for formal, casual",
    imge: "https://stylesatlife.com/wp-content/uploads/2019/05/Full-Sleeved-Red-Plain-Shirt-for-Women.jpg",
    price: "550",
    categary: "Kurta",
  },
  {
    name: "Children Shirt",
    type: "men",
    discpriton: "casual t-shirt for children",
    imge: "https://stylesatlife.com/wp-content/uploads/2017/09/Kids-Polo-Neck-T-Shirt.jpg.webp",
    price: "499",
    categary: "shirt",
  },
  {
    name: "kid Print  Shirt",
    type: "men",
    discpriton: "Print t-shirt for kids ",
    imge: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn8Qsr1ZH9vWV4dmyn5hkxs_KsCeMVbYMhlw&usqp=CAU",
    price: "900",
    categary: "shirt",
  },
  {
    name: "Kid Casual Shirt",
    type: "men",
    discpriton: "Bon Organik Beach Please Tshirts for  Boys",
    imge: "https://m.media-amazon.com/images/I/51DXEXhVl0L._UL1000_.jpg",
    price: "999",
    categary: "shirt",
  },
  {
    name: "Kid t-shirt",
    type: "men",
    discpriton: "Powerpuff - Kids The Holi Crew T-Shirts",
    imge: "https://m.media-amazon.com/images/I/51nLxOlFFkL._SL1000_.jpg",
    price: "550",
    categary: "shirt",
  },
];

export default Pdata;
